 ALTER TABLE SALARY ADD (TAX NUMBER(15));

 CREATE OR REPLACE PROCEDURE TAX_SIMPLE_LOOP_IF AS
     SUMSAL NUMBER(16);
 BEGIN
     FOR R IN (SELECT * FROM SALARY)
     LOOP
         SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
             WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

         IF SUMSAL < 20000 THEN
             UPDATE SALARY SET TAX = R.SALVALUE * 0.09
                 WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
         ELSIF SUMSAL < 30000 THEN
             UPDATE SALARY SET TAX = R.SALVALUE * 0.12
                 WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
         ELSE
             UPDATE SALARY SET TAX = R.SALVALUE * 0.15
                 WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
         END IF;
     END LOOP;
     COMMIT;
 END;

 CREATE OR REPLACE PROCEDURE TAX_CUR_LOOP_CASE AS
     SUMSAL NUMBER(16);
     CURSOR CUR IS SELECT EMPNO, SALVALUE, TAX FROM SALARY FOR UPDATE OF TAX;
     R CUR%ROWTYPE
 BEGIN
     OPEN CUR;
     LOOP
         FETCH CUR INTO R;
         EXIT WHEN CUR%NOTFOUND;
         SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
             WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

         IF SUMSAL < 20000 THEN
             UPDATE SALARY SET TAX = R.SALVALUE * 0.09
                 WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
         ELSIF SUMSAL < 30000 THEN
             UPDATE SALARY SET TAX = R.SALVALUE * 0.12
                 WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
         ELSE
             UPDATE SALARY SET TAX = R.SALVALUE * 0.15
                 WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
         END IF;
     END LOOP;
     CLOSE CUR;
     COMMIT;
 END TAX_CUR_LOOP_CASE;


 CREATE OR REPLACE PROCEDURE TAX_LOOP_CUR_CASE AS
     SUMSAL NUMBER(16);
     CURSOR CUR IS SELECT EMPNO, SALVALUE, TAX, YEAR, MONTH FROM SALARY FOR UPDATE OF TAX;
     R CUR%ROWTYPE;
 BEGIN
     OPEN CUR;
     LOOP
         FETCH CUR INTO R;
         EXIT WHEN CUR%NOTFOUND;
         SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
             WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

         UPDATE SALARY SET TAX =
             CASE
                 WHEN SUMSAL < 20000 THEN R.SALVALUE * 0.09
                 WHEN SUMSAL < 30000 THEN R.SALVALUE * 0.12
                 ELSE R.SALVALUE * 0.15
             END

             WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
     END LOOP;
     CLOSE CUR;
     COMMIT;
 END TAX_LOOP_CUR_CASE;


 CREATE OR REPLACE PROCEDURE TAX_CUR_LOOP_CASE AS
     SUMSAL NUMBER;
     CURSOR CUR IS SELECT EMPNO, SALVALUE, TAX, YEAR, MONTH FROM SALARY FOR UPDATE OF TAX;
 BEGIN
    FOR R IN CUR LOOP
          SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
             WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

         UPDATE SALARY SET TAX =
             CASE
                 WHEN SUMSAL < 20000 THEN R.SALVALUE * 0.09
                 WHEN SUMSAL < 30000 THEN R.SALVALUE * 0.12
                 ELSE R.SALVALUE * 0.15
             END

             WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
     END LOOP;
     COMMIT;
 END TAX_CUR_LOOP_CASE;


 CREATE  OR  REPLACE  PROCEDURE  TAX_PARAM (EMPID  NUMBER)  AS
     CURSOR CUR IS SELECT EMPNO, SALVALUE, TAX, YEAR, MONTH FROM SALARY
         WHERE EMPNO = EMPID
         FOR UPDATE OF TAX;
     SUMSAL NUMBER(16);
 BEGIN
     FOR R IN CUR LOOP
         SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
             WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

         UPDATE SALARY SET TAX =
             CASE
                 WHEN SUMSAL < 20000 THEN R.SALVALUE * 0.09
                 WHEN SUMSAL < 30000 THEN R.SALVALUE * 0.12
                 ELSE R.SALVALUE * 0.15
             END

             WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
     END LOOP;
     COMMIT;
 END  TAX_PARAM;

 CREATE  OR  REPLACE  PROCEDURE  TAX_PARAM_LESS (EMPID  NUMBER, UNDER_20k NUMBER,
     OVER_20k NUMBER,
     OVER_30k NUMBER)  AS
     CURSOR CUR IS SELECT EMPNO, SALVALUE, TAX, YEAR, MONTH FROM SALARY
         WHERE EMPNO = EMPID
         FOR UPDATE OF TAX;
     SUMSAL NUMBER(16);
 BEGIN
     FOR R IN CUR LOOP
         SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
             WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

         UPDATE SALARY SET TAX =
             CASE
                 WHEN SUMSAL < 20000 THEN R.SALVALUE * UNDER_20k
                 WHEN SUMSAL < 30000 THEN R.SALVALUE * OVER_20k
                 ELSE R.SALVALUE * OVER_30k
             END

             WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
     END LOOP;
     COMMIT;
 END  TAX_PARAM_LESS;

 CREATE  OR  REPLACE  FUNCTION  FTAX_PARAM_LESS (
     EMPID  NUMBER,
     UNDER_20k NUMBER,
     OVER_20k NUMBER,
     OVER_30k NUMBER) RETURN NUMBER  AS

     CURSOR CUR IS SELECT EMPNO, SALVALUE, TAX, YEAR, MONTH FROM SALARY
         WHERE EMPNO = EMPID;
     SUMSAL NUMBER(16);
     RESULT NUMBER(16);
 BEGIN
     RESULT := 0;
     FOR R IN CUR LOOP
         SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
             WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

         RESULT := RESULT +
             CASE
                 WHEN SUMSAL < 20000 THEN R.SALVALUE * UNDER_20k
                 WHEN SUMSAL < 30000 THEN R.SALVALUE * OVER_20k
                 ELSE R.SALVALUE * OVER_30k
             END;

     END LOOP;
     RETURN RESULT;
 END  FTAX_PARAM_LESS;

 SELECT FTAX_PARAM_LESS(EMPNO, 1, 2, 3) FROM SALARY

 CREATE OR REPLACE PACKAGE TAX_EVAL AS
     PROCEDURE TAX_SIMPLE_LOOP_IF();
     PROCEDURE  TAX_PARAM (EMPID  NUMBER);
     PROCEDURE  TAX_PARAM_LESS (
     UNDER_20k NUMBER,
     OVER_20k NUMBER,
     OVER_30k NUMBER,
     EMPID  NUMBER);


 END TAX_EVAL;

 CREATE OR REPLACE PACKAGE BODY TAX_EVAL AS
     PROCEDURE TAX_SIMPLE_LOOP_IF AS
         SUMSAL NUMBER(16);
     BEGIN
         FOR R IN (SELECT * FROM SALARY)
         LOOP
             SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
                 WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

             IF SUMSAL < 20000 THEN
                 UPDATE SALARY SET TAX = R.SALVALUE * 0.09
                     WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
             ELSIF SUMSAL < 30000 THEN
                 UPDATE SALARY SET TAX = R.SALVALUE * 0.12
                     WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
             ELSE
                 UPDATE SALARY SET TAX = R.SALVALUE * 0.15
                     WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
             END IF;
         END LOOP;
         COMMIT;
     END;

     PROCEDURE  TAX_PARAM (EMPID  NUMBER)  AS
     DECLARE
         CURSOR CUR IS SELECT EMPNO, SALVALUE, TAX, YEAR, MONTH FROM SALARY
             WHERE EMPNO = EMPID
             FOR UPDATE OF TAX;
         SUMSAL NUMBER(16);
     BEGIN
         LOOP R IN CUR
             SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
                 WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

             UPDATE SALARY SET TAX =
                 CASE
                     WHEN SUMSAL < 20000 THEN R.SALVALUE * 0.09
                     WHEN SUMSAL < 30000 THEN R.SALVALUE * 0.12
                     ELSE R.SALVALUE * 0.15
                 END

                 WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
         END LOOP;
         COMMIT;
     END  TAX_PARAM;

     PROCEDURE  TAX_PARAM_LESS (
     UNDER_20k NUMBER,
     OVER_20k NUMBER,
     OVER_30k NUMBER,
     EMPID  NUMBER)  AS
     DECLARE
         CURSOR CUR IS SELECT EMPNO, SALVALUE, TAX, YEAR, MONTH FROM SALARY
             WHERE EMPNO = EMPID;
         SUMSAL NUMBER(16);
     BEGIN
         LOOP R IN CUR
             SELECT SUM(SALVALUE) INTO SUMSAL FROM SALARY S
                 WHERE S.EMPNO = R.EMPNO AND S.MONTH < R.MONTH AND S.YEAR = R.YEAR;

             UPDATE SALARY SET TAX =
                 CASE
                     WHEN SUMSAL < 20000 THEN R.SALVALUE * UNDER_20k
                     WHEN SUMSAL < 30000 THEN R.SALVALUE * OVER_20k
                     ELSE R.SALVALUE * OVER_30k
                 END

                 WHERE EMPNO = R.EMPNO AND MONTH = R.MONTH AND YEAR = R.YEAR;
         END LOOP;
         COMMIT;
     END  TAX_PARAM_LESS;
 END TAX_EVAL;

 CREATE OR REPLACE TRIGGER CHECK_SALARY
     BEFORE UPDATE OF SALVALUE ON SALARY FOR EACH ROW
 DECLARE
     CUR(EMPID CAREER.EMPNO%TYPE) IS
         SELECT MINSALARY FROM JOB
             WHERE JOBNO = (SELECT JOBNO FROM CAREER WHERE EMPID = EMPNO AND ENDDATE IS NULL);
     R JOB.MINSALARY%TYPE;

 BEGIN
     OPEN CUR(:NEW.EMPNO);
     FETCH CUR INTO R;
     IF :NEW.SALVALUE < R THEN
         :NEW.SALVALUE := :OLD.SALVALUE;
     END IF;
     CLOSE CUR;
 END CHECK_SALARY;


 CREATE OR REPLACE  TRIGGER CHECK_NOT_NULL
     BEFORE DELETE ON CAREER
     FOR EACH ROW
 BEGIN
     IF OLD.ENDDATE IS NULL
         INSERT INTO CAREER VALUES (OLD.JOBNO, OLD.EMPNO, OLD.STARTDATE, OLD.ENDDATE);
     END IF;
 END CHECK_NOT_NULL;


 CREATE OR REPLACE TRIGGER ON_EMP_INSERT_UPDATE
     BEFORE INSERT OR UPDATE ON EMP
     FOR EACH ROW
 BEGIN
     IF :NEW.BIRTHDATE IS NULL THEN
         DBMS_OUTPUT.PUT_LINE('BIRTHDATE IS NULL');
     END IF;

     IF :NEW.BIRTHDATE < to_date('01-01-1940', 'dd-mm-yyyy') THEN
         DBMS_OUTPUT.PUT_LINE('PENTIONA');
     END IF;

     :NEW.EMPNAME := UPPER(:NEW.EMPNAME);
 END ON_EMP_INSERT_UPDATE;


 DECLARE
     X number;
     FUNCTION str2nr(str in varchar2) return NUMBER  IS
     BEGIN
         RETURN CAST(str AS NUMBER);
         EXCEPTION
         WHEN VALUE_ERROR THEN
             DBMS_OUTPUT.PUT_LINE('CLASS CAST EXCEPTION ' || str);
             RETURN NULL;
         WHEN OTHERS THEN
             RAISE_APPLICATION_ERROR(-20103, 'SHOULD NOT GET THERE');
         RETURN NULL;
     END;
 BEGIN
     x := str2nr( '1234123' );
     DBMS_OUTPUT.PUT_LINE(x);
     x := str2nr( '5.1' );
     DBMS_OUTPUT.PUT_LINE(x);
     x := str2nr( '4,123' );
     DBMS_OUTPUT.PUT_LINE(x);
 END;

